name: Lighthouse

on:
  push:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"

      - name: Install node_modules
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload theme
        run: node ./bin/theme-upload.js
        env:
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          BRAND_ID: ${{ secrets.BRAND_ID }}
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

      - name: Audit URLs using Lighthouse
        run: yarn test-a11y
        env:
          END_USER_EMAIL: ${{ secrets.END_USER_EMAIL }}
          END_USER_PASSWORD: ${{ secrets.END_USER_PASSWORD }}
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          URLs: |
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/categories/360002267479
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/sections/360003307259
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/articles/360010829359
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/requests/new
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/search?utf8=%E2%9C%93&query=Help+Center
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/community/topics
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/community/topics/360000644279
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/community/posts
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/community/posts/360006766799
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/profiles/364655812519
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/contributions/posts?locale=en-us
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/subscriptions
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/requests
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/requests/3
            https://${{ secrets.ZENDESK_SUBDOMAIN }}.zendesk.com/hc/en-us/community/posts/new
